# Generated by Django 4.1.11 on 2024-02-03 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_stats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stats',
        ),
    ]
