# Generated by Django 5.0.1 on 2024-01-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_player_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birthdate',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
