# Generated by Django 4.1.11 on 2024-02-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_alter_player_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birthdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
